### ISSUE TITLE
Consider Using Segues

### ISSUE THREAD

**Issue by steve228uk** [juliensagot/JSNavigationController#2]
Currently the navigation controller requires manual instantiation and for all subsequent view controllers to be manually pushed and popped. The use of storyboard segues would be a powerful addition and could even be used to define the root view controller in the same way they are used on [SRTabBarController](https://github.com/steve228uk/SRTabBarController)

**Comment by juliensagot** [comment]
Absolutely, why not!
I will work on it 👍

**Comment by steve228uk** [comment]
Awesome, let me know if I can help out at all. I started writing my own nav controller but stopped once I saw yours.

**Comment by juliensagot** [comment]
Done 👍

**Comment by steve228uk** [comment]
Nice work 😄
